create table Artifact (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, groupName varchar(255), artifactName varchar(255));
INSERT INTO Artifact (groupName, artifactName) VALUES ('org.mybatis', 'mybatis');
